AWSTemplateFormatVersion: 2010-09-09
Description: Create Listerner rules for external ALB

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Target Group Configuration"
        Parameters:
          - newPort
          - targetGroupName
          - DMZFirewallVPCID
      - Label:
          default: "Listener Rule Configuration"
        Parameters:
          - listenerArn
          - applicationDNSName
    ParameterLabels:
      newPort:
        default: New PORT number
      targetGroupName:
        default: Name for the Target Group
      DMZFirewallVPCID:
        default: VPC ID of DMZ Firewall
      listenerArn:
        default: Listern ARN for existing Public Load Balancer
      applicationDNSName:
        default: DNS name for new Application


Parameters:
  newPort:
    Description: HTTP port on which firewalls are listening
    Type: Number
  
  targetGroupName:
    Description: Name for the new target group
    Type: String

  DMZFirewallVPCID:
    Description: VPC ID associated to firewall instances
    Type: String

  listenerArn:
    Description: Provide the listener ARN to add rule for existing External Load Balancer
    Type: String

  applicationDNSName:
    Description: DNS name for the Application. (This will be used in the Load balancer listener rule)
    Type: String

Resources: 

  ## Create Target group to listen on new port for VM instances.
  targetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPort: !Ref newPort
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      Matcher:
        HttpCode: 200
      Name: !Ref targetGroupName
      Port: !Ref newPort
      Protocol: HTTP
      Tags:
        - Key: Name
          Value: !Ref targetGroupName
      TargetType: instance
      UnhealthyThresholdCount: 3
      VpcId: !Ref DMZFirewallVPCID
  
  listenerRule:
    Type: "AWS::ElasticLoadBalancingV2::ListenerRule"
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref targetGroup
      Conditions:
        - Field: host-header
          Values:
            - !Ref applicationDNSName
      ListenerArn: !Ref listenerArn
      Priority: !Ref newPort
