AWSTemplateFormatVersion: 2010-09-09
Description: Creates a Transit Gateway with two routing tables, and optional sharing through Resource Access Manager.

Parameters:
  TgwName:
    Type: String
    Default: Transit Gateway
  ShareWithOrg: 
    Type: String
    Default: 'false'
    Description: Enable sharing with all AWS Accounts in an AWS Organization
    AllowedValues: 
      - true
      - false
  OrgId: 
    Type: String
    Description: Enter Organization Id (e.g. o-12345) if Organization sharing is enabled
  MasterAccountId:
    Type: String
    Description: Account Id of master account in AWS Organization

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Transit Gateway Details
        Parameters:
          - TgwName
      - Label:
          default: (Optional) Enable sharing with an AWS Organization
        Parameters:
          - ShareWithOrg
          - OrgId
          - MasterAccountId
    ParameterLabels:
      TgwName:
        default: Transit Gateway Name
      ShareWithOrg:
        default: Enable Sharing with an Organization
      OrgId:
        default: AWS Organization Id
      MasterAccountId:
        default: Master Account Id


Conditions:
  EnableRAM: !Equals
      - !Ref ShareWithOrg
      - true

Resources: 
  Tgw:
    Type: AWS::EC2::TransitGateway
    Properties:
      AutoAcceptSharedAttachments: enable
      DefaultRouteTableAssociation: enable
      DefaultRouteTablePropagation: enable
      Description: TransitGateway
      DnsSupport: enable
      VpnEcmpSupport: enable
      Tags: 
        - Key: Name
          Value: !Ref TgwName

  TgwShare:
    Type: "AWS::RAM::ResourceShare"
    DependsOn: Tgw
    Condition: EnableRAM
    Properties:
      AllowExternalPrincipals: true
      Name: TGW-Org-Share
      Principals: 
        - !Sub 'arn:aws:organizations::${MasterAccountId}:organization/${OrgId}'
      ResourceArns: 
        - !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:transit-gateway/${Tgw}'

  TgwDMZRouteDomainId:
    Type: "AWS::EC2::TransitGatewayRouteTable"
    Properties:
      TransitGatewayId: !Ref Tgw
      Tags:
        - Key: Name
          Value: DMZ Routing Domain


Outputs:
  TransitGatewayId: 
    Description: 'TransitGateway Id'
    Value: !Ref Tgw

  TgwDMZRouteDomainId:
    Description: 'Tgw DMZ Route Domain'
    Value: !Ref TgwDMZRouteDomain
    Export:
      Name: TgwDMZRouteDomain
